CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_name VARCHAR(180) NOT NULL UNIQUE,
    project_manager_id BIGINT NOT NULL REFERENCES app_users (id),
    created_date DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE INDEX idx_projects_manager ON projects (project_manager_id);

CREATE TABLE activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_number VARCHAR(40) NOT NULL UNIQUE,
    activity_name VARCHAR(220) NOT NULL,
    project_id BIGINT NOT NULL REFERENCES projects (id),
    status VARCHAR(32) NOT NULL,
    created_date DATE NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT ck_activities_status CHECK (
        status IN (
            'ASSIGNED',
            'IN_PROGRESS',
            'FINISHED',
            'UNDER_CHECKING',
            'CORRECTION_REQUIRED',
            'CORRECTED',
            'COMPLETED'
        )
    )
);

CREATE INDEX idx_activities_project ON activities (project_id);
CREATE INDEX idx_activities_status ON activities (status);

CREATE TABLE activity_translators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id BIGINT NOT NULL REFERENCES activities (id) ON DELETE CASCADE,
    translator_id BIGINT NOT NULL REFERENCES app_users (id),
    is_responsible BOOLEAN NOT NULL DEFAULT FALSE,
    assigned_date DATE NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT uq_activity_translator UNIQUE (activity_id, translator_id)
);

CREATE INDEX idx_activity_translators_translator ON activity_translators (translator_id);
CREATE INDEX idx_activity_translators_activity ON activity_translators (activity_id);

CREATE TABLE work_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id BIGINT NOT NULL REFERENCES activities (id) ON DELETE CASCADE,
    translator_id BIGINT NOT NULL REFERENCES app_users (id),
    record_date DATE NOT NULL,
    translated_volume_pages NUMERIC(10, 2) NOT NULL,
    work_hours NUMERIC(5, 2),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_work_records_activity_translator_date UNIQUE (activity_id, translator_id, record_date),
    CONSTRAINT ck_work_records_translated_volume_pages CHECK (
        translated_volume_pages > 0 AND translated_volume_pages <= 1000
    ),
    CONSTRAINT ck_work_records_work_hours CHECK (
        work_hours IS NULL OR (work_hours >= 0 AND work_hours <= 24)
    )
);

CREATE INDEX idx_work_records_activity_translator ON work_records (activity_id, translator_id);
CREATE INDEX idx_work_records_record_date ON work_records (record_date);
